"""add_enhanced_business_fields

Revision ID: 9a8da4104e65
Revises: ad5f94e820b7
Create Date: 2025-06-22 20:28:21.316067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8da4104e65'
down_revision: Union[str, None] = 'ad5f94e820b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_results', sa.Column('reviews_count', sa.Integer(), nullable=True))
    op.add_column('scrape_results', sa.Column('reviews_average', sa.Float(), nullable=True))
    op.add_column('scrape_results', sa.Column('store_shopping', sa.String(), nullable=True))
    op.add_column('scrape_results', sa.Column('in_store_pickup', sa.String(), nullable=True))
    op.add_column('scrape_results', sa.Column('store_delivery', sa.String(), nullable=True))
    op.add_column('scrape_results', sa.Column('place_type', sa.String(), nullable=True))
    op.add_column('scrape_results', sa.Column('opening_hours', sa.String(), nullable=True))
    op.add_column('scrape_results', sa.Column('introduction', sa.Text(), nullable=True))
    op.alter_column('scrape_results', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scrape_results', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('scrape_results', 'introduction')
    op.drop_column('scrape_results', 'opening_hours')
    op.drop_column('scrape_results', 'place_type')
    op.drop_column('scrape_results', 'store_delivery')
    op.drop_column('scrape_results', 'in_store_pickup')
    op.drop_column('scrape_results', 'store_shopping')
    op.drop_column('scrape_results', 'reviews_average')
    op.drop_column('scrape_results', 'reviews_count')
    # ### end Alembic commands ###
