"""Initial tables

Revision ID: aafc687eb7a5
Revises: 
Create Date: 2025-06-16 20:40:10.203945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aafc687eb7a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('prewritten_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_jobs_id'), 'search_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_search_jobs_query'), 'search_jobs', ['query'], unique=False)
    op.create_table('outreach_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('contact_method', sa.String(), nullable=True),
    sa.Column('recipient', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['search_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['search_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_results_id'), 'scrape_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrape_results_id'), table_name='scrape_results')
    op.drop_table('scrape_results')
    op.drop_table('outreach_messages')
    op.drop_index(op.f('ix_search_jobs_query'), table_name='search_jobs')
    op.drop_index(op.f('ix_search_jobs_id'), table_name='search_jobs')
    op.drop_table('search_jobs')
    # ### end Alembic commands ###
