"""add_source_and_place_id_columns

Revision ID: cdd0035ec0f5
Revises: 3564a0a56b45
Create Date: 2025-06-20 17:05:03.719861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd0035ec0f5'
down_revision: Union[str, None] = '3564a0a56b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_results', sa.Column('place_id', sa.String(), nullable=True))
    op.add_column('search_jobs', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_jobs', 'source')
    op.drop_column('scrape_results', 'place_id')
    # ### end Alembic commands ###
